PresentationLayer/Controllers/DocumentFormController.cs
using PresentationLayer.Models;
using Rotativa;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    public class DocumentFormController : Controller
    {
        public ActionResult ForeignOffer()
        {
            return View();
        }

        public ActionResult Invoice()
        {
            return View();
        }

        public ActionResult OutgoingInvoice()
        {
            return View();
        }

        public ActionResult Offer()
        {
            return View();
        }

        public ActionResult REUSEFORM()
        {
            return View();
        }


        public ActionResult BinaryTest()
        {
            var file = new ActionAsPdf("REUSEFORM", new { name = "Giorgio" });
            var byteArray = file.BuildFile(this.ControllerContext);

            return file;

        }

        public ActionResult ReuseForm01()
        {
            var file = new ActionAsPdf("REUSEFORM11", new { name = "Giorgio" });
            var byteArray = file.BuildFile(this.ControllerContext);

            return file;

        }

        public ActionResult OutgoingInvoicePDF()
        {
            var file = new ActionAsPdf("OutgoingInvoice", new { name = "Giorgio" });
            var byteArray = file.BuildFile(this.ControllerContext);

            return file;

        }

        public ActionResult OutgoingInvoice11PDF()
        {
            var file = new ActionAsPdf("OutgoingInvoice11", new { name = "Giorgio" });
            var byteArray = file.BuildFile(this.ControllerContext);

            return file;

        }


        public ActionResult ForeignOfferPDF()
        {
            var file = new ActionAsPdf("ForeignOffer", new { name = "Giorgio" });
            var byteArray = file.BuildFile(this.ControllerContext);

            return file;

        }

        public ActionResult ForeignOffer11PDF()
        {

            var file = new ActionAsPdf("ForeignOffer11", new { name = "Giorgio" });
            var byteArray = file.BuildFile(this.ControllerContext);

            return file;

        }



        public ActionResult InvoicePDF()
        {
            var file = new ActionAsPdf("Invoice", new { name = "ASagent" });
            var byteArray = file.BuildFile(this.ControllerContext);

            return file;
        }

        public ActionResult Invoice11PDF()
        {
            var file = new ActionAsPdf("Invoice11", new { name = "ASagent" });
            var byteArray = file.BuildFile(this.ControllerContext);

            return file;
        }

        public ActionResult OfferPDF()
        {
            var file = new ActionAsPdf("Offer", new { name = "ASagent" });
            var byteArray = file.BuildFile(this.ControllerContext);

            return file;
        }

        public ActionResult Offer11PDF()
        {
            var file = new ActionAsPdf("Offer11", new { name = "ASagent" });
            var byteArray = file.BuildFile(this.ControllerContext);

            return file;
        }


        public ActionResult ForeignOffer11()
        {
            return View();
        }

        public ActionResult Invoice11()
        {
            return View();
        }

        public ActionResult OutgoingInvoice11()
        {
            return View();
        }

        public ActionResult Offer11()
        {
            return View();
        }

        public ActionResult REUSEFORM11()
        {
            return View();
        }

        public ActionResult SendEmail()
        {

            return View();
        }

        public ActionResult Pocetna()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(MailModel mailModel, HttpPostedFileBase fileUploader)
        {
            if (ModelState.IsValid)
            {
                string from = "asagentns@gmail.com";
                using (MailMessage mail = new MailMessage(from, mailModel.To))
                {
                    mail.Subject = mailModel.Subject;
                    mail.Body = mailModel.Body;
                    if (!string.IsNullOrEmpty(mailModel.Cc))
                    {
                        mail.CC.Add(mailModel.Cc);
                    }
                    if (fileUploader != null)
                    {
                        string fileName = Path.GetFileName(fileUploader.FileName);
                        mail.Attachments.Add(new Attachment(fileUploader.InputStream, fileName));
                    }
                    mail.IsBodyHtml = false;
                    SmtpClient smtp = new SmtpClient();

                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;

                    NetworkCredential networkCredential = new NetworkCredential(from, "dusanverica1983");

                    smtp.UseDefaultCredentials = true;

                    smtp.Credentials = networkCredential;

                    smtp.Port = 587;

                    smtp.Send(mail);

                    ViewBag.Message = "Sent";

                    return View("Pocetna");

                }

            }

            else

            {

                return View("Pocetna");

            }

        }




    }
    }

PresentationLayer/Controllers/DocumentationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    public class DocumentationController : Controller
    {
        // GET: Documentation
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index11()
        {
            return View();
        }
    }
}

PresentationLayer/Controllers/OutgoingInvoiceController.cs
using CommonLayer;
using PagedList;
using ServiceLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    public class OutgoingInvoiceController : Controller
    {
        IAsAgentService service1 = new AsAgentService();


        public ActionResult OutgoingInvoiceList(DateTime? dat1, DateTime? dat2, int? page)
        {
            if (dat1 != null && dat2 != null)
            {
                return View(service1.GetOutInvoicesByDate(dat1, dat2).ToPagedList(page ?? 1, 10));
            }

            var iznazneFakture = service1.OutgoingInvoices().ToPagedList(page?? 1,10);
            return View(iznazneFakture);
        }

        public ActionResult OutgoingInvoiceList11(DateTime? dat1, DateTime? dat2, int? page)
        {
            if (dat1 != null && dat2 != null)
            {
                return View(service1.GetOutInvoicesByDate(dat1, dat2).ToPagedList(page ?? 1, 10));
            }

            var iznazneFakture = service1.OutgoingInvoices().ToPagedList(page ?? 1, 10);
            return View(iznazneFakture);
        }

        public ActionResult CreateOugoingInvoice()
        {
            List<ClientDTO> klijenti = service1.AllClients().ToList<ClientDTO>();
            List<BookDTO> knjige = service1.GetBookCollection().ToList<BookDTO>();
            OutgoingInvoiceDTO dto = new OutgoingInvoiceDTO();
            dto.ClientCollection = klijenti;
            dto.BookCollection = knjige;

            return View(dto);
        }

        [HttpPost]
        public ActionResult CreateOugoingInvoice(OutgoingInvoiceDTO faktura)
        {
            var invoice = service1.GetNameOfOutgoingInvoice(faktura.NumberOfOutgoingInvoice);

            if (invoice != false)
            {
                service1.SaveInvoice(faktura);
                return RedirectToAction("OutgoingInvoiceList");
            }
            else
            {
                return RedirectToAction("CreateOugoingInvoice");
            }

        }

        public ActionResult CreateOugoingInvoice11()
        {
            List<ClientDTO> klijenti = service1.AllClients().ToList<ClientDTO>();
            List<BookDTO> knjige = service1.GetBookCollection().ToList<BookDTO>();
            OutgoingInvoiceDTO dto = new OutgoingInvoiceDTO();
            dto.ClientCollection = klijenti;
            dto.BookCollection = knjige;

            return View(dto);
        }

        [HttpPost]
        public ActionResult CreateOugoingInvoice11(OutgoingInvoiceDTO faktura)
        {
            var invoice = service1.GetNameOfOutgoingInvoice(faktura.NumberOfOutgoingInvoice);

            if (invoice != false)
            {
                service1.SaveInvoice(faktura);
                return RedirectToAction("OutgoingInvoiceList11");
            }
            else
            {
                return RedirectToAction("CreateOugoingInvoice11");
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            List<BookDTO> books = service1.GetBookCollection().ToList<BookDTO>();
            List<ClientDTO> clients = service1.AllClients().ToList<ClientDTO>();

            var invoice = service1.FindIInvoiceById(id);
            OutgoingInvoiceDTO dto = new OutgoingInvoiceDTO();
            dto.OutgoingInvoiceId = id;
            dto.DateOfReceipt = invoice.DateOfReceipt;
            dto.NumberOfOutgoingInvoice = invoice.NumberOfOutgoingInvoice;
            dto.AmountDIN = invoice.AmountDIN;
            dto.AmountInEUR = invoice.AmountInEUR;
            dto.ValueDate = invoice.ValueDate;
            dto.PaymentDate = invoice.PaymentDate;
            dto.Paid = invoice.Paid;
            dto.Comment = invoice.Comment;
            dto.BookId = invoice.BookId;
            dto.ClientId = invoice.ClientId;
            dto.BookCollection = books;
            dto.ClientCollection = clients;

            return View(dto);

        }

        [HttpPost]
        public ActionResult Edit(OutgoingInvoiceDTO dto)
        {

            service1.SaveChangesOfInvoice(dto);
            return RedirectToAction("OutgoingInvoiceList");

        }

        [HttpPost]
        public ActionResult DeleteInvoice(int id)
        {
            service1.DeleteOutInvoice(id);
            return RedirectToAction("OutgoingInvoiceList");
        }

        [HttpGet]
        public ActionResult Edit11(int id)
        {
            List<BookDTO> books = service1.GetBookCollection().ToList<BookDTO>();
            List<ClientDTO> clients = service1.AllClients().ToList<ClientDTO>();

            var invoice = service1.FindIInvoiceById(id);
            OutgoingInvoiceDTO dto = new OutgoingInvoiceDTO();
            dto.OutgoingInvoiceId = id;
            dto.DateOfReceipt = invoice.DateOfReceipt;
            dto.NumberOfOutgoingInvoice = invoice.NumberOfOutgoingInvoice;
            dto.AmountDIN = invoice.AmountDIN;
            dto.AmountInEUR = invoice.AmountInEUR;
            dto.ValueDate = invoice.ValueDate;
            dto.PaymentDate = invoice.PaymentDate;
            dto.Paid = invoice.Paid;
            dto.Comment = invoice.Comment;
            dto.BookId = invoice.BookId;
            dto.ClientId = invoice.ClientId;
            dto.BookCollection = books;
            dto.ClientCollection = clients;

            return View(dto);

        }

        [HttpPost]
        public ActionResult Edit11(OutgoingInvoiceDTO dto)
        {

            service1.SaveChangesOfInvoice(dto);
            return RedirectToAction("OutgoingInvoiceList11");

        }

        [HttpPost]
        public ActionResult DeleteInvoice11(int id)
        {
            service1.DeleteOutInvoice(id);
            return RedirectToAction("OutgoingInvoiceList11");
        }
    }
}

PresentationLayer/Views/DocumentForm/Pocetna.cshtml
@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" charset="UTF-8" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <link href="~/Style/dokumentacija.css" rel="stylesheet" />
    <title>KNJIGA NALOGA</title>

</head>
<body>
    <div class="container">

        <a href="@Url.Action("Invoice", "DocumentForm")">
            <img class="slika" src="~/Images/fromadomacafaktura.png" />
        </a>
        <a href="@Url.Action("OutgoingInvoice", "DocumentForm")">
            <img class="slika" src="~/Images/formainofaktura.png" />
        </a>

        <a href="@Url.Action("Offer", "DocumentForm")">
            <img class="slika" src="~/Images/domacaponuda.png" />
        </a>
        <a href="@Url.Action("ForeignOffer", "DocumentForm")">
            <img class="slika" src="~/Images/inoponuda.png" />
        </a>
        <a href="@Url.Action("REUSEFORM", "DocumentForm")">
            <img class="slika" src="~/Images/reuseform.png" />
        </a>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

PresentationLayer/Views/DocumentForm/REUSEFORM.cshtml
@{
    ViewBag.Title = "ASagent";
    //if (Session["userID"] == null)
    //{
    //    Response.Redirect("~/User/Landing");
    //}
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <style type="text/css">
        body {
            margin: 0px;
            padding: 0px;
            font-family: Calibri;
            background-color: white;
            font-size: 0.7em;
        }

        .content {
            color: grey;
            overflow: auto;
            max-width: 900px;
            margin: auto;
            background: white;
        }

        h2 {
            font-weight: bold;
            font-size: 1.5em;
            text-align: center;
            padding-bottom: 20px;
        }

        #header {
            padding-top: 20px;
            font-size: 1.3em;
        }

        #firstPart {
            float: left;
            padding-left: 10px;
        }

        #secondPart {
            float: left;
            padding-left: 40px;
        }

            #secondPart p {
                padding-bottom: 10px;
            }

        #middle {
            float: left;
            font-size: 1.3em;
            padding-left: 10px;
            padding-top: 5px;
            text-align: justify;
        }

        .sp {
            padding-left: 50px;
        }

        #bottom {
            padding-top: 20px;
            float: left;
            padding-left: 10px;
            color: black;
        }

        label {
            float: left;
            padding-right: 15px;
            font-size: 1.3em;
        }

        input {
            float: left;
        }

        .di {
            float: left;
            margin-bottom: 5px;
            border-bottom: 1px solid black;
        }

        #container {
            font-weight: bold;
            font-size: 1.3em;
        }

        #booking {
            font-weight: bold;
            font-size: 1.3em;
            margin-left: 12px;
        }

        #date {
            font-weight: bold;
            font-size: 1.3em;
            margin-left: 23px;
        }

        #lbl {
            font-weight: normal;
            color: grey;
            margin-top: 50px;
            font-size: 1em;
            padding-right: 0px !important;
        }

        label {
            font-size: 1em;
        }

        #buttons {
            padding-top: 120px;
        }

        #l {
            float: left;
            padding-right: 25px;
        }

        .btn {
            background-color: lightblue;
            color: dodgerblue;
            height: 2em;
            border: 1px solid lightblue;
            margin-right: 10px;
        }
    </style>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script type="text/javascript">

        function printpage() {

            var printButton = document.getElementById("printpagebutton");
            var save = document.getElementById("pdfSave");
            var back = document.getElementById("btnNazad");


            var text = document.getElementById("container");
            var text1 = document.getElementById("booking");
            var text2 = document.getElementById("date");

            printButton.style.visibility = 'hidden';
            back.style.visibility = 'hidden';
            save.style.visibility = 'hidden';

            text.style.border = "none";
            text.style.background = "transparent";

            text1.style.border = "none";
            text1.style.background = "transparent";

            text2.style.border = "none";
            text2.style.background = "transparent";

            window.print()

        };

    </script>

</head>
<body>
    <div class="content">
        <h2>CONTAINER RE-USE FORM</h2>
        <div id="header">
            <div id="firstPart"><p>To:</p></div>
            <div id="secondPart">
                <p>A.P.Moller c/0 A.P.M&empty;ller - Maersk A/S</p>
                <p>Esplanaden 50 DK - 1098 Copenhagen</p>
                <p>As owners and/or chartwrers of the S.S./M.V.  ............................</p>
                <p>FROM: AS AGENT D.O.O.</p>
                <span>(hereafter referred to as Contractor)</span>
            </div>
        </div>
        <br />
        <div id="middle">
            <p>
                Whereas the term "container" shall in this Form mean, but is not limited to, any container including reefer
                containers, van or box used by the ML for the carriage of goods, merchandise and cargo of any size, weight or
                dimensions;<br />
                Whereas the term "Inspection/Pre Trip Inspection" shall in this Form mean the inspection normally carried out by
                ML on empty containers before release to customers, in order to ensure that a container is fit for carriage of goods;<br />
                WHEREAS the Contractor has a need to re-use container received from ML containing cargo, for re-stuffing and
                exporting form time to time, without said containers being returned to ML for Inspection, Contractor shall have
                such a right provided this Form is signed on the conditions as follows:
            </p>
            <p>
                1.<span class="sp">
                    Contractor hereby acknowledges that in those cases where a container released to Contractor for un-
                    stuffing, is re-used by Contractor for new cargo, ML have been deprived of its possibility to perform Inspection/Pre
                    Trip Inspection on said container.
                </span>
            </p>
            <p>
                2.<span class="sp">
                    Contractor hereby agrees that for those instances, it shall automatically be assumed that the container
                    was fit for carriage of goods when gated out for un-stuffing, and save where Contractor proves that the container
                    was still sound and fit for use when delivered back to ML for export, it shall be assumed that any damage must
                    have occurred before or during stuffing by Contractor for export.
                </span>
            </p>
            <p>
                3.<span class="sp">
                    Contractor has a duty to inspect Containers before packing them and the use of Containers shall be prima
                    facie evidence of their being sound and suitable for use, wherefore ML shall have no liability whatsoever for any
                    damage arisen directly or indirectly from such damage.
                </span>
            </p>
            <p>
                3.<span class="sp">
                    Should such a claim raise, Contractor hereby agrees and undertakes to indemnify and hold harmless ML
                    for any and all claims arising from such damage.
                </span>
            </p>
        </div>
        <div id="bottom">
            <div class="di">
                <label>Container number</label><input id="container" type="text" style="margin-left:10px;"/>
            </div><br />
            <div class="di">
                <label>Booking number</label><input id="booking" type="text" style="margin-left:18px;"/>
            </div><br />
            <div class="di">
                <label>Date / Location</label><input type="text" id="date" />
            </div>
            <div id="special">
                <label id="lbl">
                    Company Stamp /<br />
                    Authorised Signature
                </label><img style="width:150px;height:100px;" src="~/Images/signature.jpg" />
            </div>

            <div id="buttons">


                <div id="l">
                    <input class="btn" id="printpagebutton" type="button" value="Štampaj" onclick="printpage()" />
                    <button type="button" id="btnNazad" class="btn" onclick="location.href='@Url.Action("Index","Documentation")'">Nazad</button>
                    <button type="button" class="btn" id="pdfSave" onclick="location.href='@Url.Action("BinaryTest", "DocumentForm")'">PDF</button>
                </div>
            </div>
        </div>

    </div>

</body>
</html>

PresentationLayer/Views/DocumentForm/REUSEFORM11.cshtml
@{
    /**/

    ViewBag.Title = "ASagent";
    //if (Session["userID"] == null)
    //{
    //    Response.Redirect("~/User/Landing");
    //}
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <style type="text/css">
        body {
            margin: 0px;
            padding: 0px;
            font-family: Calibri;
            background-color: white;
            font-size: 0.7em;
        }

        .content {
            color: grey;
            overflow: auto;
            max-width: 900px;
            margin: auto;
            background: white;
        }

        h2 {
            font-weight: bold;
            font-size: 1.5em;
            text-align: center;
            padding-bottom: 20px;
        }

        #header {
            padding-top: 20px;
            font-size: 1.3em;
        }

        #firstPart {
            float: left;
            padding-left: 10px;
        }

        #secondPart {
            float: left;
            padding-left: 40px;
        }

            #secondPart p {
                padding-bottom: 10px;
            }

        #middle {
            float: left;
            font-size: 1.3em;
            padding-left: 10px;
            padding-top: 5px;
            text-align: justify;
        }

        .sp {
            padding-left: 50px;
        }

        #bottom {
            padding-top: 20px;
            float: left;
            padding-left: 10px;
            color: black;
        }

        label {
            float: left;
            padding-right: 15px;
            font-size: 1.3em;
        }

        input {
            float: left;
        }

        .di {
            float: left;
            margin-bottom: 5px;
            border-bottom: 1px solid black;
        }

        #container {
            font-weight: bold;
            font-size: 1.3em;
        }

        #booking {
            font-weight: bold;
            font-size: 1.3em;
            margin-left: 12px;
        }

        #date {
            font-weight: bold;
            font-size: 1.3em;
            margin-left: 23px;
        }

        #lbl {
            font-weight: normal;
            color: grey;
            margin-top: 50px;
            font-size: 1em;
            padding-right: 0px !important;
        }

        label {
            font-size: 1em;
        }

        #buttons {
            padding-top: 120px;
        }

        #l {
            float: left;
            padding-right: 25px;
        }

        .btn {
            background-color: lightblue;
            color: dodgerblue;
            height: 2em;
            border: 1px solid lightblue;
            margin-right: 10px;
        }
    </style>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script type="text/javascript">

        function printpage() {

            var printButton = document.getElementById("printpagebutton");
            var save = document.getElementById("pdfSave");
            var back = document.getElementById("btnNazad");


            var text = document.getElementById("container");
            var text1 = document.getElementById("booking");
            var text2 = document.getElementById("date");

            printButton.style.visibility = 'hidden';
            back.style.visibility = 'hidden';
            save.style.visibility = 'hidden';

            text.style.border = "none";
            text.style.background = "transparent";

            text1.style.border = "none";
            text1.style.background = "transparent";

            text2.style.border = "none";
            text2.style.background = "transparent";

            window.print()

        };

    </script>

</head>
<body>
    <div class="content">
        <h2>CONTAINER RE-USE FORM</h2>
        <div id="header">
            <div id="firstPart"><p>To:</p></div>
            <div id="secondPart">
                <p>A.P.Moller c/0 A.P.M&empty;ller - Maersk A/S</p>
                <p>Esplanaden 50 DK - 1098 Copenhagen</p>
                <p>As owners and/or chartwrers of the S.S./M.V.  ............................</p>
                <p>FROM: AS AGENT D.O.O.</p>
                <span>(hereafter referred to as Contractor)</span>
            </div>
        </div>
        <br />
        <div id="middle">
            <p>
                Whereas the term "container" shall in this Form mean, but is not limited to, any container including reefer
                containers, van or box used by the ML for the carriage of goods, merchandise and cargo of any size, weight or
                dimensions;<br />
                Whereas the term "Inspection/Pre Trip Inspection" shall in this Form mean the inspection normally carried out by
                ML on empty containers before release to customers, in order to ensure that a container is fit for carriage of goods;<br />
                WHEREAS the Contractor has a need to re-use container received from ML containing cargo, for re-stuffing and
                exporting form time to time, without said containers being returned to ML for Inspection, Contractor shall have
                such a right provided this Form is signed on the conditions as follows:
            </p>
            <p>
                1.<span class="sp">
                    Contractor hereby acknowledges that in those cases where a container released to Contractor for un-
                    stuffing, is re-used by Contractor for new cargo, ML have been deprived of its possibility to perform Inspection/Pre
                    Trip Inspection on said container.
                </span>
            </p>
            <p>
                2.<span class="sp">
                    Contractor hereby agrees that for those instances, it shall automatically be assumed that the container
                    was fit for carriage of goods when gated out for un-stuffing, and save where Contractor proves that the container
                    was still sound and fit for use when delivered back to ML for export, it shall be assumed that any damage must
                    have occurred before or during stuffing by Contractor for export.
                </span>
            </p>
            <p>
                3.<span class="sp">
                    Contractor has a duty to inspect Containers before packing them and the use of Containers shall be prima
                    facie evidence of their being sound and suitable for use, wherefore ML shall have no liability whatsoever for any
                    damage arisen directly or indirectly from such damage.
                </span>
            </p>
            <p>
                3.<span class="sp">
                    Should such a claim raise, Contractor hereby agrees and undertakes to indemnify and hold harmless ML
                    for any and all claims arising from such damage.
                </span>
            </p>
        </div>
        <div id="bottom">
            <div class="di">
                <label>Container number</label><input id="container" type="text" style="margin-left:10px;"/>
            </div><br />
            <div class="di">
                <label>Booking number</label><input id="booking" type="text" style="margin-left:18px;"/>
            </div><br />
            <div class="di">
                <label>Date / Location</label><input type="text" id="date" />
            </div>
            <div id="special">
                <label id="lbl">
                    Company Stamp /<br />
                    Authorised Signature
                </label><img style="width:150px;height:100px;" src="~/Images/signature.jpg" />
            </div>

            <div id="buttons">


                <div id="l">
                    <input class="btn" id="printpagebutton" type="button" value="Štampaj" onclick="printpage()" />
                    <button type="button" id="btnNazad" class="btn" onclick="location.href='@Url.Action("Index","Documentation")'">Nazad</button>
                    <button type="button" class="btn" id="pdfSave" onclick="location.href='@Url.Action("ReuseForm01", "DocumentForm")'">PDF</button>
                </div>
            </div>
        </div>

    </div>

</body>
</html>