PresentationLayer/Controllers/ParnterPonudaController.cs
using CommonLayer;
using DataLayer;
using ServiceLayer;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    public class ParnterPonudaController : Controller
    {
        IAsAgentService service1 = new AsAgentService();

        // GET: ParnterPonuda
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListaPonuda()
        {
            var ponude = service1.GetAllOffers();
            return View(ponude);
        }

       

        [HttpGet]
        public ActionResult KreirajPonudu()
        {
            var lista = service1.GetPartners();
            PartnerPonudaDTO dto = new PartnerPonudaDTO();

            foreach(var p in lista)
            {
                //PartnerDTO dtopa = (PartnerDTO)p;
                PartnerDTO dtop = new PartnerDTO(((PartnerDTO)p).PartnerId, ((PartnerDTO)p).Pib, ((PartnerDTO)p).Naziv, ((PartnerDTO)p).Ime, ((PartnerDTO)p).Prezime, ((PartnerDTO)p).Adresa,
                   ((PartnerDTO)p).Email, ((PartnerDTO)p).Telefon,  ((PartnerDTO)p).Drzava);

                //dtop staviti u listu i onda gore proslediti u dto
                dto.PartnerItems.Add(new SelectListItem { Value = dtop.PartnerId.ToString(), Text = dtop.Naziv} );
            }
            
            return View(dto);
        }

        [HttpPost]
        public ActionResult KreirajPonudu(PartnerPonudaDTO partnerii)
        {
            try
            {
                PartnerPonudaDTO partnerDto = new PartnerPonudaDTO();
                //partnerDto.PartnerId = Int32.Parse(partnerii.ListaPartnera.SelectedValue);
                //partnerDto.Nazivpartnera = partnerii.First().Text;
                partnerDto.Id = 3333;
                partnerDto.NazivPonude = "nazivPonude3333";
                partnerDto.Opis = "djadjadadadadad";
                partnerDto.Cena = 266;
                partnerDto.Datum = DateTime.Now;

                service1.SavePartnerOffer(partnerDto);
            }
            catch (Exception )
            {
                throw;
            }
            return RedirectToAction("ListaPonuda");
        }

        [HttpPost]
        public ActionResult DeleteOffer(int id)
        {
            service1.DeletePartnerOffer(id);
            return RedirectToAction("ListaPonuda");
        }
    }
}

PresentationLayer/Views/ParnterPonuda/KreirajPonudu.cshtml
@model CommonLayer.PartnerPonudaDTO

@{
    ViewBag.Title = "KreirajPonudu";
}

<h2>KreirajPonudu</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PartnerPonudaDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.PartnerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartnerId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartnerId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.NazivPonude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NazivPonude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NazivPonude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m =>m.SelectedPartnerId)
            <div class="col-md-10">
              
                @Html.DropDownListFor(m => m.SelectedPartnerId, Model.PartnerItems)
                @Html.ValidationMessageFor(m => m.SelectedPartnerId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PresentationLayer/Views/ParnterPonuda/ListaPonuda.cshtml
@model IEnumerable<CommonLayer.PartnerPonudaDTO>

@{
    ViewBag.Title = "ListaPonuda";
}

<h2>ListaPonuda</h2>

<p>
    <button type="button" onclick="location.href='@Url.Action("KreirajPonudu","ParnterPonuda")'">Dodaj ponudu</button>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NazivPonude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nazivpartnera)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Datum)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    using (Html.BeginForm("DeleteOffer", "ParnterPonuda", new { id = item.Id }))
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NazivPonude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nazivpartnera)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Opis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cena)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Datum)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            <input type="submit" value="Delete" onclick="return confirm('Da li zelite da obrisete racun  @item.NazivPonude')" />
        </td>
    </tr>
    }
}
</table>