PresentationLayer/Controllers/AsaBookingNumberController.cs
using CommonLayer;
using PagedList;
using ServiceLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    public class AsaBookingNumberController : Controller
    {
        IAsAgentService service1 = new AsAgentService();

        // GET: AsaBookingNumber
        public ActionResult ASAList(int? page)
        {
            var lista = service1.GetAllAsaNumbers().ToPagedList(page?? 1,10);
            return View(lista);
        }

        public ActionResult ASAList11(int? page)
        {
            var lista = service1.GetAllAsaNumbers().ToPagedList(page ?? 1, 10);
            return View(lista);
        }

        [HttpGet]
        public ActionResult AddAsaBookingNumber()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAsaBookingNumber(ASABookingNumberDTO dto)
        {
            service1.SaveAsaBookingNumber(dto);
            return RedirectToAction("ASAList");

        }

        [HttpGet]
        public ActionResult AddAsaBookingNumber11()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAsaBookingNumber11(ASABookingNumberDTO dto)
        {
            service1.SaveAsaBookingNumber(dto);
            return RedirectToAction("ASAList11");

        }

        public ActionResult Edit(int id)
        {
            var number = service1.AsaBookingNumberById(id);

            return View(number);
        }

        public ActionResult Edit11(int id)
        {
            var number = service1.AsaBookingNumberById(id);

            return View(number);
        }

        [HttpPost]
        public ActionResult Edit(ASABookingNumberDTO dto)
        {

            service1.SaveAsaBookingNumberChanges(dto);
            return RedirectToAction("ASAList");

        }

        [HttpPost]
        public ActionResult Edit11(ASABookingNumberDTO dto)
        {

            service1.SaveAsaBookingNumberChanges(dto);
            return RedirectToAction("ASAList11");

        }

        [HttpPost]
        public ActionResult DeleteAsaBookingNumber(int id)
        {
            service1.DeleteAsaBookingNumber(id);
            return RedirectToAction("ASAList");
        }

        [HttpPost]
        public ActionResult DeleteAsaBookingNumber11(int id)
        {
            service1.DeleteAsaBookingNumber(id);
            return RedirectToAction("ASAList11");
        }
    }
}

PresentationLayer/Controllers/BookController.cs
using CommonLayer;
using PagedList;
using ServiceLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    public class BookController : Controller
    {
        IAsAgentService service1 = new AsAgentService();

        public ActionResult Index(int? page, string sortBy)
        {
            ViewBag.SortDateParametar = string.IsNullOrEmpty(sortBy) ? "Name desc" : "";
            ViewBag.SortBookObjectParametar = sortBy == "ObjectBook" ? "ObjectBook desc" : "ObjectBook";

            //var knjige = service1.GetBookCollection().ToPagedList(page?? 1,10);

            var books = service1.GetBookCollection().AsQueryable();
            foreach (var k in books)
            {
                k.ClientName = service1.GetNameOfClientByBookId(k.BookId);
                k.PriceOfInputInvoice = service1.GetPriceOfInputInvoice(k.BookId) + service1.GetPriceOfForeignInputInovice(k.BookId);
                k.AsaPrice = service1.GetPriceOfOutgoingInvoice(k.BookId) + service1.GetPriceOfForeignOutgoingInvoice(k.BookId);
                k.Difference = k.AsaPrice - k.PriceOfInputInvoice;
            }

            switch (sortBy)
            {
                case "Name desc":
                    books = books.OrderByDescending(x => x.DateOfLoading);
                    break;
                case "ObjectBook desc":
                    books = books.OrderByDescending(x => x.ObjectBook);
                    break;
                case "Name":
                    books = books.OrderBy(x => x.DateOfLoading);
                    break;
                default:
                    books = books.OrderBy(x => x.ObjectBook);
                    break;
            }
           
            return View(books.ToPagedList(page?? 1,10));
        }

        public ActionResult Index11(int? page, string sortBy)
        {
            ViewBag.SortDateParametar = string.IsNullOrEmpty(sortBy) ? "Name desc" : "";
            ViewBag.SortBookObjectParametar = sortBy == "ObjectBook" ? "ObjectBook desc" : "ObjectBook";

            //var knjige = service1.GetBookCollection().ToPagedList(page?? 1,10);

            var books = service1.GetBookCollection().AsQueryable();
            foreach (var k in books)
            {
                k.ClientName = service1.GetNameOfClientByBookId(k.BookId);
                k.PriceOfInputInvoice = service1.GetPriceOfInputInvoice(k.BookId) + service1.GetPriceOfForeignInputInovice(k.BookId);
                k.AsaPrice = service1.GetPriceOfOutgoingInvoice(k.BookId) + service1.GetPriceOfForeignOutgoingInvoice(k.BookId);
                k.Difference = k.AsaPrice - k.PriceOfInputInvoice;
            }

            switch (sortBy)
            {
                case "Name desc":
                    books = books.OrderByDescending(x => x.DateOfLoading);
                    break;
                case "ObjectBook desc":
                    books = books.OrderByDescending(x => x.ObjectBook);
                    break;
                case "ObjectBook":
                    books = books.OrderBy(x => x.ObjectBook);
                    break;
                default:
                    books = books.OrderBy(x => x.DateOfLoading);
                    break;
            }

            return View(books.ToPagedList(page ?? 1, 10));
        }


        public ActionResult AddBook()
        {
            List<ASABookingNumberDTO> asaBookingNumbers = service1.GetAllAsaNumbers();
            List<StandardBookingNumberDTO> obicanBookingNumbers = service1.GetAllStandardNumbers();

            BookDTO dto = new BookDTO();

            dto.AsaCollection = asaBookingNumbers;

            dto.StandardCollection = obicanBookingNumbers;
            return View(dto);
        }

        [HttpPost]
        public ActionResult AddBook(BookDTO dto)
        {
                service1.SaveBook(dto);
                return RedirectToAction("Index");

        }

        public ActionResult AddBook11()
        {
            List<ASABookingNumberDTO> asaBookingNumbers = service1.GetAllAsaNumbers();
            List<StandardBookingNumberDTO> obicanBookingNumbers = service1.GetAllStandardNumbers();

            BookDTO dto = new BookDTO();

            dto.AsaCollection = asaBookingNumbers;

            dto.StandardCollection = obicanBookingNumbers;
            return View(dto);
        }

        [HttpPost]
        public ActionResult AddBook11(BookDTO dto)
        {
            service1.SaveBook(dto);
            return RedirectToAction("Index11");

        }



        [HttpGet]
        public ActionResult Edit(int id)
        {
            var b = service1.BookById(id);
            BookDTO dto = new BookDTO();
            dto.BookId = b.BookId;
            dto.ObjectBook = b.ObjectBook;
            dto.PlaceOfLoading = b.PlaceOfLoading;
            dto.DateOfLoading = b.DateOfLoading;
            dto.PlaceOfUnloading = b.PlaceOfUnloading;
            dto.Goods = b.Goods;
            dto.Customer = b.Customer;
            dto.QuantityOfGoods = b.QuantityOfGoods;
            dto.ContainerTruck = b.ContainerTruck;
            dto.BookingNumber = b.BookingNumber;

            return View(dto);

        }

        [HttpPost]
        public ActionResult Edit(BookDTO dto)
        { 
                service1.SaveBookChanges(dto);
                return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit11(int id)
        {
            var b = service1.BookById(id);
            BookDTO dto = new BookDTO();
            dto.BookId = b.BookId;
            dto.ObjectBook = b.ObjectBook;
            dto.PlaceOfLoading = b.PlaceOfLoading;
            dto.DateOfLoading = b.DateOfLoading;
            dto.PlaceOfUnloading = b.PlaceOfUnloading;
            dto.Goods = b.Goods;
            dto.Customer = b.Customer;
            dto.QuantityOfGoods = b.QuantityOfGoods;
            dto.ContainerTruck = b.ContainerTruck;
            dto.BookingNumber = b.BookingNumber;

            return View(dto);

        }

        [HttpPost]
        public ActionResult Edit11(BookDTO dto)
        {
            service1.SaveBookChanges(dto);
            return RedirectToAction("Index11");
        }

        public ActionResult OutInvoicesList(int id)
        {
            InvoiceMultipleDTO myModel = new InvoiceMultipleDTO();
            myModel.OutInvoices = service1.GetOutInvoicesByBookId(id);
            myModel.OutInoInvoices = service1.GetOutInoInvoicesByBookId(id);

            return View(myModel);
        }

        public ActionResult ShowTableOfInvoices(int id)
        {
            InvoiceMultipleDTO myModel = new InvoiceMultipleDTO();
            myModel.InputInvoices = service1.GetInvoiceByBookId(id);
            myModel.ForeignInputInvoices = service1.GetInoInvoiceByBookId(id);
            return View(myModel);
        }

        [HttpPost]
        public ActionResult DeleteBook(int id)
        {
            service1.DeleteBook(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteBook11(int id)
        {
            service1.DeleteBook(id);
            return RedirectToAction("Index11");
        }

        public ActionResult OutInvoicesList11(int id)
        {
            InvoiceMultipleDTO myModel = new InvoiceMultipleDTO();
            myModel.OutInvoices = service1.GetOutInvoicesByBookId(id);
            myModel.OutInoInvoices = service1.GetOutInoInvoicesByBookId(id);

            return View(myModel);
        }

        public ActionResult ShowTableOfInvoices11(int id)
        {
            InvoiceMultipleDTO myModel = new InvoiceMultipleDTO();
            myModel.InputInvoices = service1.GetInvoiceByBookId(id);
            myModel.ForeignInputInvoices = service1.GetInoInvoiceByBookId(id);
            return View(myModel);
        }


    }
}

PresentationLayer/Views/AsaBookingNumber/ASAList.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<CommonLayer.ASABookingNumberDTO>

@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
   
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/cost.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/search.js"></script>
    <title>KORISNICI</title>
</head>
<body>
    <div id="login-div">
        <h1 style="font-family:Calibri;margin-top:50px;">ASA BOOKING BROJEVI</h1>

        @using (Html.BeginForm("ASAList", "AsaBookingNumber", FormMethod.Get))
        {
            <div class="dugmici" style="float:right;padding-right:70px;">
                <button type="button" style="width:30px; height:30px;border-radius:30px; color:white; background-color:#64B2D4;" onclick="location.href='@Url.Action("Index", "Book")'">KN</button>
                </div>
            <div align="right" style="margin-bottom: 1em;">
                <input type="text" id="myInput" class="form-control" onkeyup="myFunction()" style="font-family:Calibri" placeholder="Pretraži...">
            </div>
        }
        <table id="myTable">
            <tr style="border:1px groove; text-align: center">
                <th class="table-bordered1" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().AsaNumber)
                </th>
                <th class="table-bordered2" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().Distance)
                </th>
                <th class="table-bordered1" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().Container)
                </th>
                <th class="table-bordered2"></th>
            </tr>

            @foreach (var item in Model)
            {
                using (Html.BeginForm("DeleteAsaBookingNumber", "AsaBookingNumber", new { id = item.AsaBookingNumberId }))
                {
                    <tr>
                        <td class="table-bordered" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.AsaNumber)
                        </td>
                        <td class="table-bordered" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.Distance)
                        </td>
                        <td class="table-bordered" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.Container)
                        </td>
                        <td class="table-bordered" id="tra">
                            <a href="@Url.Action("Edit", "AsaBookingNumber", new { id = item.AsaBookingNumberId })">
                                <img src="~/Images/edit.png" style="float:left; padding-right:5px; width:25px;" />
                            </a>
                            <input style="width:25px;" type="image" src="~/Images/delete.png" onclick="return confirm('Da li zelite da izbrisete broj @item.AsaNumber')" />
                        </td>
                    </tr>
                }
            }
        </table>
        <div class="paginacija">
            @Html.PagedListPager(Model, page => Url.Action("ASAList", new { page, @class = "paginacija" }),
       new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
        </div>
        <button id="button-add" type="button" style="font-family:Calibri" onclick="location.href='@Url.Action("AddAsaBookingNumber","AsaBookingNumber")'">Dodaj</button>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

PresentationLayer/Views/AsaBookingNumber/ASAList11.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<CommonLayer.ASABookingNumberDTO>

@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/cost.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/search.js"></script>
    <title>KORISNICI</title>
</head>
<body>
    <div id="login-div">
        <h1 style="font-family:Calibri;margin-top:50px;">ASA BOOKING BROJEVI</h1>

        @using (Html.BeginForm("ASAList11", "AsaBookingNumber", FormMethod.Get))
        {
            <div class="dugmici" style="float:right;padding-right:70px;">
                <button type="button" style="width:30px; height:30px;border-radius:30px; color:white; background-color:#64B2D4;" onclick="location.href='@Url.Action("Index", "Book")'">KN</button>
            </div>
            <div align="right" style="margin-bottom: 1em;">
                <input type="text" id="myInput" class="form-control" onkeyup="myFunction()" style="font-family:Calibri" placeholder="Pretraži...">
            </div>
        }
        <table id="myTable">
            <tr style="border:1px groove; text-align: center">
                <th class="table-bordered1" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().AsaNumber)
                </th>
                <th class="table-bordered2" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().Distance)
                </th>
                <th class="table-bordered1" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().Container)
                </th>
                <th class="table-bordered2"></th>
            </tr>

            @foreach (var item in Model)
            {
                using (Html.BeginForm("DeleteAsaBookingNumber11", "AsaBookingNumber", new { id = item.AsaBookingNumberId }))
                {
                    <tr>
                        <td class="table-bordered" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.AsaNumber)
                        </td>
                        <td class="table-bordered" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.Distance)
                        </td>
                        <td class="table-bordered" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.Container)
                        </td>
                        <td class="table-bordered" id="tra">
                            <a href="@Url.Action("Edit", "AsaBookingNumber", new { id = item.AsaBookingNumberId })">
                                <img src="~/Images/edit.png" style="float:left; padding-right:5px; width:25px;" />
                            </a>
                            <input style="width:25px;" type="image" src="~/Images/delete.png" onclick="return confirm('Da li zelite da izbrisete broj @item.AsaNumber')" />
                        </td>
                    </tr>
                }
            }
        </table>
        <div class="paginacija">
            @Html.PagedListPager(Model, page => Url.Action("ASAList11", new { page, @class = "paginacija" }),
            new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
        </div>
        <button id="button-add" type="button" style="font-family:Calibri" onclick="location.href='@Url.Action("AddAsaBookingNumber11","AsaBookingNumber")'">Dodaj</button>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

PresentationLayer/Views/AsaBookingNumber/AddAsaBookingNumber.cshtml
@model CommonLayer.ASABookingNumberDTO

@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/table1.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>ASA BOOKING BROJ</title>
</head>
<body>

    <div class="container" style="padding-left:350px;">
        <h2 style="font-family:Calibri">KREIRAJ ASA BROJ</h2>
        <br />

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @*<div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AsaNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Asa booking broj..." } })

                        </div>
                    </div>*@

                <div class="form-group">

                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Distance, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri", placeholder = "Relacija..." } })
                        @Html.ValidationMessageFor(model => model.Distance, "", new { @class = "text-danger", @style = "font-family:Calibri" })
                    </div>
                </div>

                <div class="form-group">

                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Container, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri", placeholder = "Kontejner..." } })
                        @Html.ValidationMessageFor(model => model.Container, "", new { @class = "text-danger", @style = "font-family:Calibri" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" style="font-family:Calibri" onclick="location.href='@Url.Action("ASAList", "AsaBookingNumber")'">Nazad</button>
                        <input type="submit" style="font-family:Calibri" value="Kreiraj" class="create-btn" />
                    </div>
                </div>
            </div>
        }
    </div>
</body>
</html>

PresentationLayer/Views/AsaBookingNumber/AddAsaBookingNumber11.cshtml
@model CommonLayer.ASABookingNumberDTO

@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/table1.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>ASA BOOKING BROJ</title>
</head>
<body>

    <div class="container" style="padding-left:350px;">
        <h2 style="font-family:Calibri">KREIRAJ ASA BROJ</h2>
        <br />

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @*<div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.AsaNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Asa booking broj..." } })

                        </div>
                    </div>*@

                <div class="form-group">

                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Distance, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri", placeholder = "Relacija..." } })
                        @Html.ValidationMessageFor(model => model.Distance, "", new { @class = "text-danger", @style = "font-family:Calibri" })
                    </div>
                </div>

                <div class="form-group">

                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Container, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri", placeholder = "Kontejner..." } })
                        @Html.ValidationMessageFor(model => model.Container, "", new { @class = "text-danger", @style = "font-family:Calibri" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" style="font-family:Calibri" onclick="location.href='@Url.Action("ASAList11", "AsaBookingNumber")'">Nazad</button>
                        <input type="submit" style="font-family:Calibri" value="Kreiraj" class="create-btn" />
                    </div>
                </div>
            </div>
        }
    </div>
</body>
</html>

PresentationLayer/Views/AsaBookingNumber/Edit.cshtml
@model CommonLayer.ASABookingNumberDTO

@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/table1.css" rel="stylesheet" />
    <title>PARTNERI</title>
</head>
<body>
    <h2 style="padding-left:570px;">IMENI PODATKE O ASA BROJU</h2>
    <div class="container" style="padding-left:350px;">


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @*@Html.LabelFor(model => model.AsaBookingNumberId, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AsaBookingNumberId, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri" } })
                        @Html.ValidationMessageFor(model => model.AsaBookingNumberId, "", new { @class = "text-danger", @style = "font-family:Calibri" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AsaNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AsaNumber, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.AsaNumber, "", new { @class = "text-danger", @style = "font-family:Calibri" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Distance, htmlAttributes: new { @class = "control-label col-md-2", @style = "font-family:Calibri" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Distance, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri" } })
                        @Html.ValidationMessageFor(model => model.Distance, "", new { @class = "text-danger", @style = "font-family:Calibri" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Container, htmlAttributes: new { @class = "control-label col-md-2", @style = "font-family:Calibri" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Container, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri" } })
                        @Html.ValidationMessageFor(model => model.Container, "", new { @class = "text-danger", @style = "font-family:Calibri" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" style="font-family:Calibri;"  onclick="location.href='@Url.Action("ASAList", "AsaBookingNumber")'">Nazad</button>
                        <input type="submit" style="font-family:Calibri;" value="Sačuvaj" class="create-btn" />             
                    </div>
                </div>
            </div>
        }

    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>