PresentationLayer/Controllers/CostController.cs
using CommonLayer;
using PagedList;
using ServiceLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    public class CostController : Controller
    {
        IAsAgentService service1 = new AsAgentService();

        public ActionResult CostList(string racun, DateTime? date1, DateTime? date2, int? page)
        {
            ViewBag.troskovi = service1.AllCosts();

            if (date1 != null && date2 != null)
            {
                return View(service1.GetCostByDate(date1, date2));
            }
            else if (racun != null)
            {
                return View(service1.FilterCostsByName(racun));
            }

            var troskovi = service1.AllCosts().ToPagedList(page?? 1, 10);
            return View(troskovi);
        }

        public ActionResult CostList11(string racun, DateTime? date1, DateTime? date2, int? page)
        {
            ViewBag.troskovi = service1.AllCosts();

            if (date1 != null && date2 != null)
            {
                return View(service1.GetCostByDate(date1, date2));
            }
            else if (racun != null)
            {
                return View(service1.FilterCostsByName(racun));
            }

            var troskovi = service1.AllCosts().ToPagedList(page ?? 1, 10);
            return View(troskovi);
        }

        [HttpGet]
        public ActionResult AddCost()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCost(CostsDTO dto)
        {
            try
            {
                service1.SaveCost(dto);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("CostList");
        }

        [HttpGet]
        public ActionResult AddCost11()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCost11(CostsDTO dto)
        {
            try
            {
                service1.SaveCost(dto);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("CostList11");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var trosak = service1.FindCostById(id);
            CostsDTO dto = new CostsDTO();
            dto.CostId = id;
            dto.AccountNumber = trosak.AccountNumber;
            dto.DateOfReceipt = trosak.DateOfReceipt;
            dto.PaymentDate = trosak.PaymentDate;
            dto.Amount = trosak.Amount;
            dto.Paid = trosak.Paid;

            return View(dto);
        }

        [HttpPost]
        public ActionResult Edit(CostsDTO trosak)
        {
            if (ModelState.IsValid)
            {
                service1.SaveCostChanges(trosak);
                return RedirectToAction("CostList");
            }

            return View(trosak);
        }

        [HttpGet]
        public ActionResult Edit11(int id)
        {
            var trosak = service1.FindCostById(id);
            CostsDTO dto = new CostsDTO();
            dto.CostId = id;
            dto.AccountNumber = trosak.AccountNumber;
            dto.DateOfReceipt = trosak.DateOfReceipt;
            dto.PaymentDate = trosak.PaymentDate;
            dto.Amount = trosak.Amount;
            dto.Paid = trosak.Paid;

            return View(dto);
        }

        [HttpPost]
        public ActionResult Edit11(CostsDTO trosak)
        {
            if (ModelState.IsValid)
            {
                service1.SaveCostChanges(trosak);
                return RedirectToAction("CostList11");
            }

            return View(trosak);
        }

        [HttpPost]
        public ActionResult DeleteCost(int id)
        {
            service1.DeleteCost(id);
            return RedirectToAction("CostList");
        }

        [HttpPost]
        public ActionResult DeleteCost11(int id)
        {
            service1.DeleteCost(id);
            return RedirectToAction("CostList11");
        }
    }
}

PresentationLayer/Views/Cost/AddCost.cshtml
@model CommonLayer.CostsDTO

@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/table1.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>IZLAZNA FAKTURA</title>
</head>
<body>

    <div class="container" style="padding-left:350px;">
        <h2 style="font-family:Calibri;">KREIRAJ TROŠAK</h2>
        <br />

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">


                @Html.ValidationSummary(true, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AccountNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Račun...", @style = "font-family:Calibri;" } })
                        @Html.ValidationMessageFor(model => model.AccountNumber, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateOfReceipt, htmlAttributes: new { @class = "control-label col-md-2", @style = "font-family:Calibri;" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateOfReceipt, new { htmlAttributes = new { @class = "form-control", @type = "date", @style = "font-family:Calibri;" } })
                        @Html.ValidationMessageFor(model => model.DateOfReceipt, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PaymentDate, htmlAttributes: new { @class = "control-label col-md-2", @style = "font-family:Calibri;" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control", @type = "date", @style = "font-family:Calibri;" } })
                        @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2", @style = "font-family:Calibri;" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Paid, htmlAttributes: new { @class = "control-label col-md-2", @style = "font-family:Calibri;" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Paid)
                            @Html.ValidationMessageFor(model => model.Paid, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" style="font-family:Calibri;" onclick="location.href='@Url.Action("CostList", "Cost")'">Nazad</button>
                        <input type="submit" style="font-family:Calibri;" value="Kreiraj" class="create-btn" />
                    </div>
                </div>
            </div>
        }
    </div>
    
</body>
</html>

PresentationLayer/Views/Cost/AddCost11.cshtml
@model CommonLayer.CostsDTO

@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
   
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/table1.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>IZLAZNA FAKTURA</title>
</head>
<body>

    <div class="container" style="padding-left:350px;">
        <h2 style="font-family:Calibri;">KREIRAJ TROŠAK</h2>
        <br />

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">


                @Html.ValidationSummary(true, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AccountNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Račun...", @style = "font-family:Calibri;" } })
                        @Html.ValidationMessageFor(model => model.AccountNumber, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateOfReceipt, htmlAttributes: new { @class = "control-label col-md-2", @style = "font-family:Calibri;" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateOfReceipt, new { htmlAttributes = new { @class = "form-control", @type = "date", @style = "font-family:Calibri;" } })
                        @Html.ValidationMessageFor(model => model.DateOfReceipt, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PaymentDate, htmlAttributes: new { @class = "control-label col-md-2", @style = "font-family:Calibri;" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control", @type = "date", @style = "font-family:Calibri;" } })
                        @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2", @style = "font-family:Calibri;" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Paid, htmlAttributes: new { @class = "control-label col-md-2", @style = "font-family:Calibri;" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Paid)
                            @Html.ValidationMessageFor(model => model.Paid, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" style="font-family:Calibri;" onclick="location.href='@Url.Action("CostList11", "Cost")'">Nazad</button>
                        <input type="submit" style="font-family:Calibri;" value="Kreiraj" class="create-btn" />
                    </div>
                </div>
            </div>
        }
    </div>

</body>
</html>

PresentationLayer/Views/Cost/CostList.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<CommonLayer.CostsDTO>

@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
  
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/cost.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/search.js"></script>
    <title>TROSKOVI</title>
</head>
<body>
    <div id="login-div" class="table-responsive">
        <h2 style="font-family:Calibri;margin-top:50px;">TROŠKOVI</h2>
        <br />
        @using (Html.BeginForm("CostList", " Cost", FormMethod.Get))
        {
            <div align="right" style="margin-bottom: 1em;">
                <input type="text" id="myInput" class="form-control" style="font-family:Calibri" onkeyup="myFunction()" placeholder="Pretraži..">
            </div>
        }
        <table id="myTable">
            <tr style="border:1px groove; text-align: center">
                <th class="table-bordered1" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().AccountNumber)
                </th>
                <th class="table-bordered2" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().DateOfReceipt)
                </th>
                <th class="table-bordered1" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().PaymentDate)
                </th>
                <th class="table-bordered2" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().Amount)
                </th>
                <th class="table-bordered1" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().Paid)
                </th>
                <th class="table-bordered2"></th>
            </tr>

            @foreach (var item in Model)
            {
                using (Html.BeginForm("DeleteCost", "Cost", new { id = item.CostId }))
                {
                    <tr>
                        <td class="table-bordered3" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.AccountNumber)
                        </td>
                        <td class="table-bordered" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.DateOfReceipt)
                        </td>
                        <td class="table-bordered3" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.PaymentDate)
                        </td>
                        <td class="table-bordered" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                        <td class="table-bordered3" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.Paid)
                        </td>
                        <td class="table-bordered" id="bla">
                            <a href="@Url.Action("Edit", "Cost", new { id = item.CostId })">
                                <img src="~/Images/edit.png" style="float:left; padding-right:5px; width:25px;" />
                            </a>
                            <input style="width:25px;" type="image" src="~/Images/delete.png" onclick="return confirm('Da li zelite da izbrisete  @item.AccountNumber ')" />
                        </td>
                    </tr>
                }
            }
        </table>
        <div class="paginacija">
            @Html.PagedListPager(Model, page => Url.Action("CostList", new { page, @class = "paginacija" }),
       new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
        </div>
        <button id="button-add" type="button" style="font-family:Calibri" onclick="location.href='@Url.Action("AddCost","Cost")'">Dodaj</button>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>

PresentationLayer/Views/Cost/CostList11.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<CommonLayer.CostsDTO>

@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
   
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/cost.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/search.js"></script>
    <title>TROSKOVI</title>
</head>
<body>
    <div id="login-div" class="table-responsive">
        <h2 style="font-family:Calibri;margin-top:50px;">TROŠKOVI</h2>
        <br />
        @using (Html.BeginForm("CostList11", " Cost", FormMethod.Get))
        {
            <div align="right" style="margin-bottom: 1em;">
                <input type="text" id="myInput" class="form-control" style="font-family:Calibri" onkeyup="myFunction()" placeholder="Pretraži..">
            </div>
        }
        <table id="myTable">
            <tr style="border:1px groove; text-align: center">
                <th class="table-bordered1" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().AccountNumber)
                </th>
                <th class="table-bordered2" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().DateOfReceipt)
                </th>
                <th class="table-bordered1" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().PaymentDate)
                </th>
                <th class="table-bordered2" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().Amount)
                </th>
                <th class="table-bordered1" style="font-family:Calibri">
                    @Html.DisplayNameFor(model => model.First().Paid)
                </th>
                <th class="table-bordered2"></th>
            </tr>

            @foreach (var item in Model)
            {
                using (Html.BeginForm("DeleteCost11", " Cost", new { id = item.CostId }))
                {
                    <tr>
                        <td class="table-bordered3" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.AccountNumber)
                        </td>
                        <td class="table-bordered" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.DateOfReceipt)
                        </td>
                        <td class="table-bordered3" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.PaymentDate)
                        </td>
                        <td class="table-bordered" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                        <td class="table-bordered3" style="font-family:Calibri">
                            @Html.DisplayFor(modelItem => item.Paid)
                        </td>
                        <td class="table-bordered" id="bla">
                            <a href="@Url.Action("Edit11", "Cost", new { id = item.CostId })">
                                <img src="~/Images/edit.png" style="float:left; padding-right:5px; width:25px;" />
                            </a>
                            <input style="width:25px;" type="image" src="~/Images/delete.png" onclick="return confirm('Da li zelite da izbrisete  @item.AccountNumber ')" />
                        </td>
                    </tr>
                }
            }
        </table>
        <div class="paginacija">
            @Html.PagedListPager(Model, page => Url.Action("CostList11", new { page, @class = "paginacija" }),
       new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
        </div>
        <button id="button-add" type="button" style="font-family:Calibri" onclick="location.href='@Url.Action("AddCost11","Cost")'">Dodaj</button>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>

PresentationLayer/Views/Cost/Edit.cshtml
@model CommonLayer.CostsDTO

@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
   
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/table1.css" rel="stylesheet" />
    <title>TROSKOVI</title>
</head>
<body>
    <h2 style="padding-left:580px;font-family:Calibri;">IZMENI  PODATKE O TROSKU</h2>
    <div class="container" style="padding-left:350px;">

        <br />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">


                @Html.ValidationSummary(true, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                @Html.HiddenFor(model => model.CostId)
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CostId, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.AccountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AccountNumber, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateOfReceipt, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateOfReceipt, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Paid, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Paid)

                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" style="font-family:Calibri;" onclick="location.href='@Url.Action("CostList", "Cost")'">Nazad</button>
                        <input type="submit" style="font-family:Calibri;" value="Sačuvaj" class="create-btn" />
                    </div>
                </div>
            </div>
        }
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>

PresentationLayer/Views/Cost/Edit11.cshtml
@model CommonLayer.CostsDTO

@{
    ViewBag.Title = "ASagent";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
  
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/table1.css" rel="stylesheet" />
    <title>TROSKOVI</title>
</head>
<body>
    <h2 style="padding-left:580px;font-family:Calibri;">IZMENI  PODATKE O TROSKU</h2>
    <div class="container" style="padding-left:350px;">

        <br />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">


                @Html.ValidationSummary(true, "", new { @class = "text-danger", @style = "font-family:Calibri;" })
                @Html.HiddenFor(model => model.CostId)
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CostId, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.AccountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AccountNumber, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateOfReceipt, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateOfReceipt, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PaymentDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PaymentDate, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @style = "font-family:Calibri;" } })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Paid, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Paid)

                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" style="font-family:Calibri;" onclick="location.href='@Url.Action("CostList11", "Cost")'">Nazad</button>
                        <input type="submit" style="font-family:Calibri;" value="Sačuvaj" class="create-btn" />
                    </div>
                </div>
            </div>
        }
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>